name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        node-version: '20'  # Ensure the use of Node.js 20

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        node-version: '20'  # Ensure the use of Node.js 20

    - name: Build with Maven
      run: mvn -B compile --file pom.xml

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        node-version: '20'  # Ensure the use of Node.js 20

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        node-version: '20'  # Ensure the use of Node.js 20

    - name: Test with Maven
      run: mvn test

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        node-version: '20'  # Ensure the use of Node.js 20

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        node-version: '20'  # Ensure the use of Node.js 20

    - name: Package with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: target/*.jar
